# Generated by Django 3.2.8 on 2021-10-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='type your description', max_length=150),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='feature1', max_length=100),
        ),
    ]
